/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcercaDeMiRouteImport } from './routes/acerca-de-mi'
import { Route as AdminPanelRouteImport } from './routes/admin-panel'
import { Route as ElLibroRouteImport } from './routes/el-libro'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as HablemosRouteImport } from './routes/hablemos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcercaDeMiRoute = AcercaDeMiRouteImport.update({
  id: '/acerca-de-mi',
  path: '/acerca-de-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin-panel',
  path: '/admin-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ElLibroRoute = ElLibroRouteImport.update({
  id: '/el-libro',
  path: '/el-libro',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const HablemosRoute = HablemosRouteImport.update({
  id: '/hablemos',
  path: '/hablemos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acerca-de-mi': typeof AcercaDeMiRoute
  '/admin-panel': typeof AdminPanelRoute
  '/el-libro': typeof ElLibroRoute
  '/favoritos': typeof FavoritosRoute
  '/hablemos': typeof HablemosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acerca-de-mi': typeof AcercaDeMiRoute
  '/admin-panel': typeof AdminPanelRoute
  '/el-libro': typeof ElLibroRoute
  '/favoritos': typeof FavoritosRoute
  '/hablemos': typeof HablemosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acerca-de-mi': typeof AcercaDeMiRoute
  '/admin-panel': typeof AdminPanelRoute
  '/el-libro': typeof ElLibroRoute
  '/favoritos': typeof FavoritosRoute
  '/hablemos': typeof HablemosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acerca-de-mi'
    | '/admin-panel'
    | '/el-libro'
    | '/favoritos'
    | '/hablemos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acerca-de-mi'
    | '/admin-panel'
    | '/el-libro'
    | '/favoritos'
    | '/hablemos'
  id:
    | '__root__'
    | '/'
    | '/acerca-de-mi'
    | '/admin-panel'
    | '/el-libro'
    | '/favoritos'
    | '/hablemos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcercaDeMiRoute: typeof AcercaDeMiRoute
  AdminPanelRoute: typeof AdminPanelRoute
  ElLibroRoute: typeof ElLibroRoute
  FavoritosRoute: typeof FavoritosRoute
  HablemosRoute: typeof HablemosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acerca-de-mi': {
      id: '/acerca-de-mi'
      path: '/acerca-de-mi'
      fullPath: '/acerca-de-mi'
      preLoaderRoute: typeof AcercaDeMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panel': {
      id: '/admin-panel'
      path: '/admin-panel'
      fullPath: '/admin-panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el-libro': {
      id: '/el-libro'
      path: '/el-libro'
      fullPath: '/el-libro'
      preLoaderRoute: typeof ElLibroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hablemos': {
      id: '/hablemos'
      path: '/hablemos'
      fullPath: '/hablemos'
      preLoaderRoute: typeof HablemosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcercaDeMiRoute: AcercaDeMiRoute,
  AdminPanelRoute: AdminPanelRoute,
  ElLibroRoute: ElLibroRoute,
  FavoritosRoute: FavoritosRoute,
  HablemosRoute: HablemosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
